"""Seed headings for the weekly recap sections. New entries are added to the DB on startup."""

COMPLETION_HEADINGS = [
    "Completion wins // Closing loops",
    "Done and dusted // Loops closed",
    "Shipped // Out the door",
    "Checked off // Nothing pending",
    "Finished business // Loose ends tied",
    "Crossed the line // Finished strong",
    "Wrapped up // Signed and sealed",
    "Put to bed // Case closed",
    "Nailed it // Finished pieces",
    "Landed // Things that touched down",
    "Closed tickets // Nothing left hanging",
    "Delivered // Promises kept",
    "Mission complete // Objectives cleared",
    "Final touches // Brought home",
    "Knocked out // Off the list",
    "Box ticked // Done deal",
    "Across the finish line // Complete",
    "Sealed // Loops that won't reopen",
    "Out in the wild // Released",
    "Completed quests // XP earned",
    "Boss fights won // Levels cleared",
    "Signed off // Approved and done",
    "In the bag // Secured",
    "Tied the knot // Loose ends handled",
    "Clean finishes // Zero leftovers",
    "Mic drop // Finished pieces",
    "That's a wrap // Scenes completed",
    "Harvest // What came to fruition",
    "Last mile // Got it over the line",
    "Merged // Into main",
    "Shipped to prod // Live now",
    "Closed chapters // Stories finished",
    "Full stop // Sentences ended",
    "Wrapped and ready // Handed over",
    "Buttoned up // Neat and done",
    "Squared away // Settled",
    "Put a bow on it // Gift-wrapped",
    "Loop, meet close // Completed",
    "Cleared the deck // Nothing pending",
    "Trophies // Things I finished",
    "Victory lap // Done this week",
    "Checkered flag // Race finished",
    "Final whistle // Match over",
    "Curtain call // Performances done",
    "Last page // Books closed",
    "Cooked // Fully done",
    "Out of the oven // Baked through",
    "Ready to serve // Finished dishes",
    "Released // Set free",
    "Launched // Lift-off achieved",
    "Touchdown // Landed safely",
    "Goal // Back of the net",
    "Home run // Rounded all bases",
    "Slam dunk // Nothing but net",
    "Checkmate // Game won",
    "Mission accomplished // Debrief",
    "Solved // Puzzles finished",
    "Unlocked // Achievements earned",
    "Level up // Stages cleared",
    "Loot secured // Rewards claimed",
    "Wins banked // Saved and done",
    "Pinned down // Finalized",
    "Locked in // No going back",
    "Finalized // Last version out",
    "Signed, sealed, delivered // Done",
    "Out of my hands // Delivered",
    "Handed off // Passed along complete",
    "Done list // Not a todo list",
    "Ta-da // Finished things",
    "Receipts // Proof of completion",
    "Stamped // Officially done",
    "Filed away // Complete and archived",
    "Closed the tab // One less open",
    "Committed // Changes finalized",
    "Deployed // Running in the wild",
    "Built // From scratch to finish",
    "Finished builds // Green checks",
    "All green // Tests passing, tasks done",
    "Inbox zero // Cleared out",
    "Paid off // Debts closed",
    "Resolved // Issues closed",
    "Fixed // Bugs squashed",
    "Squashed // Bugs gone",
    "Tidied // Clean slate",
    "Settled // Things finished",
    "Endings // Loops that closed",
    "The done pile // Growing taller",
    "Completed tracks // Album finished",
    "Final cut // Edits done",
    "Printed // Off the press",
    "Published // Out there now",
    "Closed deals // Handshakes done",
    "Crossed off // Pen through the line",
    "Struck through // List items gone",
    "Ticks all round // Checked",
    "Done done // Not almost done",
    "Actually finished // No asterisks",
    "100% // Not 99",
    "Full bar // Progress maxed",
    "Topped off // Filled to the brim",
    "Summit // Reached the top",
    "Peak reached // View from the top",
    "Flag planted // Territory claimed",
    "Docked // Ship in harbor",
    "Arrived // Destinations reached",
    "Journey's end // Made it",
    "Closing time // Doors shut",
    "Lights out // Shift finished",
    "Clocked out // Tasks done",
    "Handled // Taken care of",
    "Sorted // In order and done",
    "Kept promises // Word delivered",
    "Followed through // All the way",
    "Saw it through // To the end",
    "Got it done // No excuses",
    "Made it happen // Real results",
    "Tangible // Things you can touch now",
    "Proof of work // Blocks mined",
    "Crafted // Made complete",
    "Polished // Shined and finished",
    "Final form // Fully evolved",
    "Graduated // Moved out of todo",
    "Promoted // From draft to done",
    "Out of beta // Stable now",
    "v1.0 // Stable release",
    "Feature complete // Scope closed",
    "Closed out // Books balanced",
    "End of story // Loops finished",
    "Happy endings // Things concluded",
    "Concluded // Final answers",
    "Answered // Questions closed",
    "Full circle // Loops complete",
    "Clean exits // Left nothing behind",
    "Last stroke // Finished lines",
    "Trophy shelf // Shelved as done",
    "The finish line // Crossed",
    "Nothing left // Cleared",
    "Wrapped // Out of the queue",
    "Queue cleared // All processed",
    "Burned down // Backlog shrinking",
    "Knocked down // Pins fallen",
    "Strike // All pins down",
    "Bullseye // Right on target",
    "Hit the mark // Delivered on target",
    "Closed the gap // Finished",
    "Sealed the deal // Done",
    "Wrapped the week // Completed",
    "Payday // Work that paid off",
    "Cashed in // Results collected",
    "Collected // Wins in hand",
    "Finish line photos // Done and proud",
]

PROGRESS_HEADINGS = [
    "Progress wins // Moving something forward",
    "In motion // Things rolling",
    "Momentum // Picking up speed",
    "Step by step // Getting closer",
    "Brick by brick // Walls rising",
    "Underway // Moving along",
    "On the move // Forward only",
    "No reverse gear // Forward only",
    "Inching ahead // Small steps count",
    "Small steps // Still counting",
    "Groundwork // Foundations laid",
    "Seeds planted // Growing soon",
    "Sprouting // Early growth",
    "Leveling up // XP gained",
    "Charging // Battery filling",
    "Loading // Progress bar moving",
    "Progress bar // Creeping right",
    "Halfway there // Keep going",
    "Warming up // Engines running",
    "Revving // Engines on",
    "Gaining ground // Territory taken",
    "Advancing // Pushing the line",
    "Pushing forward // Heads down",
    "Heads down // Grinding",
    "The grind // Work in progress",
    "Work in progress // Not done, not stuck",
    "WIP // Wheels turning",
    "Wheels turning // Rolling on",
    "Snowball // Getting bigger",
    "Stacking // Blocks piling up",
    "Compounding // Small gains adding up",
    "Drafts // Rough but real",
    "Rough cuts // Shaping up",
    "Taking shape // Coming together",
    "Coming together // Pieces fitting",
    "Puzzle pieces // Fitting in",
    "Sketches // Outlines drawn",
    "Blueprints // Plans on paper",
    "Scaffolding // Structure going up",
    "Under construction // Hard hats on",
    "Construction zone // Progress ahead",
    "Miles covered // Journey continues",
    "Milestones // Markers passed",
    "Checkpoints // Saved progress",
    "Save point // Progress stored",
    "Chipping away // One bit at a time",
    "Carving // Shape emerging",
    "Sculpting // Form appearing",
    "Digging deeper // Getting there",
    "Learning curve // Climbing it",
    "Climbing // Higher each week",
    "Altitude // Gaining height",
    "Base camp // Preparing the climb",
    "Trailblazing // New paths",
    "Exploring // Uncharted bits",
    "Scouting // Recon done",
    "Experiments // Trying things",
    "Prototypes // Early versions",
    "Iterating // Better each round",
    "Sharpening // Edges honed",
    "Tuning // Dialing in",
    "Dialing in // Closer to right",
    "Calibrating // Almost aligned",
    "Lining up // Dominoes set",
    "Setting the stage // Prep work",
    "Mise en place // Ingredients ready",
    "Simmering // Cooking slowly",
    "Slow cook // Flavors developing",
    "Marinating // Ideas soaking",
    "Brewing // Something's coming",
    "Fermenting // Give it time",
    "Incubating // Warming ideas",
    "Hatching // Cracks appearing",
    "Budding // About to bloom",
    "Growing roots // Stronger base",
    "Watering // Tending the garden",
    "Nurturing // Growing things",
    "Training // Reps in",
    "Reps // Getting stronger",
    "Practice // Getting better",
    "Gains // Small but real",
    "Steady pace // Keeping it even",
    "Consistency // Showing up",
    "Showing up // Again and again",
    "Streak alive // Unbroken",
    "Needle moved // Measurably",
    "Nudges // Small pushes",
    "Traction // Grip gained",
    "Footing // Steadier now",
    "Stepping stones // Crossing over",
    "Bridges // Being built",
    "Paving // Road getting smoother",
    "Clearing the way // Obstacles moved",
    "Unblocked // Free to move",
    "Unstuck // Moving again",
    "Breakthroughs // Walls cracked",
    "Headway // Made some",
    "Forward motion // Progress report",
    "Green light // Go go go",
    "Full steam // Ahead",
    "Accelerating // Faster now",
    "Tempo // Rhythm found",
    "In the groove // Flow state",
    "Riding the wave // Keeping balance",
    "Stroke by stroke // Across the water",
    "Still writing // Pages added",
    "To be continued // More next week",
    "Stay tuned // More coming",
    "Opening moves // Game on",
    "Positioning // Pieces placed",
    "Long game // Playing it",
    "Laying track // Train coming",
    "Pipeline // Flowing",
    "In the oven // Not done yet",
    "Half baked // In the best way",
    "Groundbreaking // Shovels in",
    "First drafts // Words on the page",
    "Outlines // The shape of things",
    "Research mode // Learning the terrain",
    "Mapping // Charting the route",
    "Routing // Finding the way",
    "Wayfinding // Direction set",
    "Compass set // Heading true north",
    "Course correcting // Still on track",
    "On track // Rolling ahead",
    "Picking up pace // Faster week",
    "Tailwind // Pushed forward",
    "Uphill // Still climbing",
    "Grinding gears // Getting smoother",
    "Oiling the machine // Running better",
    "Assembling // Parts coming in",
    "Wiring up // Connecting pieces",
    "Plugging in // Powering up",
    "Booting up // Almost live",
    "Compiling // Build in progress",
    "Rendering // Frames coming in",
    "Downloading // Percent climbing",
    "Buffering // Worth the wait",
    "Queued up // Next in line",
    "Pre-launch // Countdown started",
    "Countdown // T-minus something",
    "Fueling up // Tanks filling",
    "Stretching // Getting ready to sprint",
    "Jogging // Warm legs",
    "Mid-race // Still running",
    "Second wind // Back at it",
    "Keeping at it // No quitting",
    "Planting flags // Along the way",
    "Laying bricks // Wall going up",
    "Stirring the pot // Things cooking",
]
